variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - deploy

# Partie backend (java)
.java-base: &java-base
  image: maven:3.8-openjdk-17
  before_script:
    - cd backend || exit 1

java-build:
  <<: *java-base
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

java-test:
  <<: *java-base
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

java-deploy:
  <<: *java-base
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests

# Partie frontend (nodejs)

# TODO : add frontend build, test and deploy
build:
  stage: build

  image: trion/ng-cli

  before_script:
    - npm ci

  script:
    - ng build

  artifacts:
    expire_in: 1 day

    paths:
      - dist/

  tags:
    - dind

test:karma:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  script:
    - npm i
    - ng test --progress false --watch false
  tags:
    - dind
