variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

cache:
    paths:
        - .m2/repository
        - front/frontAD512Back/node_modules

stages:
  - build
  - test
  - deploy

# Partie backend (java)
.java-base: &java-base
  image: maven:3.8-openjdk-17
  before_script:
    - cd backend || exit 1

java-build:
  <<: *java-base
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

java-test:
  <<: *java-base
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

java-deploy:
  <<: *java-base
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS package -DskipTests

# Partie frontend (nodejs)
node-build:
  stage: build
  image: trion/ng-cli
  before_script:
    - cd front/frontAD512Bank/ || exit 1
    - npm ci
  script:
    - ng build

node-test:
  stage: test
  image: trion/ng-cli-karma
  allow_failure: false
  before_script:
    - cd front/frontAD512Bank/ || exit 1
    - npm ci
  script:
    - ng test --progress false --watch false
